version: "0.0.1"
services:
  chaos-app:
    container_name: chaos-app
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /data/db
    ports:
      - "27017:27017"